apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tb-http-loadbalancer
  namespace: thingsboard
spec:
  defaultBackend:
    service:
      name: tb-edge
      port:
        number: 8080
