#
# Copyright © 2016-2021 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-ui-redpanda
spec:
  serviceName: kafka-ui-redpanda
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui-redpanda
  template:
    metadata:
      labels:
        app: kafka-ui-redpanda
    spec:
      containers:
        - name: server
          imagePullPolicy: Always
          image: docker.redpanda.com/redpandadata/console:latest
          resources:
            requests:
              cpu: 50m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 8080
              name: http8080
          env:
            - name: KAFKA_BROKERS
              value: "tb-kafka:9092" # put your broker list here. By default - tb-kafka:9092
      restartPolicy: Always
